'use client'

import { useEffect, useMemo, useState } from 'react'
import { ChevronLeft, ChevronRight, Maximize2, Pause, Play, RefreshCw, RotateCcw, Trophy } from 'lucide-react'
import { fetchDashboardData } from '@/lib/google-script'

type Candidate = { name?: string; nama?: string; namaKetua?: string; namaWakil?: string; photoKetua?: string; photoWakil?: string; image?: string; foto?: string; photo?: string; votes?: number; color?: string }
type Vote = { candidateName?: string; candidate?: string }
type Data = { candidates?: Candidate[]; votes?: Vote[]; totalVoters?: number; sessionStatus?: string }
type ReplayCandidate = Candidate & { label: string; count: number; color: string }

const colors = ['#7657e8', '#e27b58', '#2fa994', '#d4a13a']
const stages = [20, 50, 80, 100]
const candidateName = (candidate: Candidate) => candidate.name || candidate.nama || `Paslon ${candidate.namaKetua || ''}`
const candidateImages = (candidate: Candidate) => [candidate.photoKetua || candidate.image || candidate.foto || candidate.photo || '', candidate.photoWakil || '']

export default function VoteReplay({ initialData }: { initialData: Data }) {
  const [data, setData] = useState(initialData)
  const [stageIndex, setStageIndex] = useState(0)
  const [playing, setPlaying] = useState(true)
  const [loading, setLoading] = useState(false)
  const [updated, setUpdated] = useState(new Date())
  const votes = data.votes || []
  const stage = stages[stageIndex]
  const visibleVotes = useMemo(() => votes.slice(0, Math.ceil(votes.length * stage / 100)), [votes, stage])
  const candidates = useMemo<ReplayCandidate[]>(() => {
    const counts = visibleVotes.reduce<Record<string, number>>((acc, vote) => { const key = vote.candidateName || vote.candidate || ''; acc[key] = (acc[key] || 0) + 1; return acc }, {})
    return (data.candidates || []).map((candidate, index) => ({ ...candidate, label: candidateName(candidate), count: counts[candidateName(candidate)] || 0, color: candidate.color || colors[index % colors.length] })).sort((a, b) => b.count - a.count)
  }, [data.candidates, visibleVotes])
  const totalVotes = votes.length || data.totalVoters || 0
  const total = votes.length ? visibleVotes.length : Math.ceil(totalVotes * stage / 100)
  const refresh = async () => { setLoading(true); try { const next = await fetchDashboardData(); if (next.result === 'success') { setData(next); setStageIndex(0) }; setUpdated(new Date()) } catch { setUpdated(new Date()) } finally { setLoading(false) } }
  useEffect(() => { if (!playing) return; const timer = window.setTimeout(() => { if (stageIndex < stages.length - 1) setStageIndex(index => index + 1); else setPlaying(false) }, 5000); return () => window.clearTimeout(timer) }, [playing, stageIndex])
  const goFullscreen = () => document.documentElement.requestFullscreen?.()
  const reset = () => { setStageIndex(0); setPlaying(true) }
  return <main className="min-h-screen overflow-hidden bg-[#100d1f] text-white selection:bg-[#7657e8]">
    <header className="flex items-center justify-between border-b border-white/10 px-6 py-5 sm:px-10 lg:px-16"><div className="flex items-center gap-3"><img src="https://cdn.zakilabs.my.id/pemilos/logoosis.png" alt="Logo OSIS" className="size-11 object-contain"/><div><p className="text-sm font-bold tracking-wide">SMAZA<span className="text-[#a696ff]">16</span></p><p className="text-[10px] uppercase tracking-[.24em] text-white/45">Pemilihan Ketua OSIS</p></div></div><div className="flex items-center gap-3"><span className="hidden text-xs text-white/45 sm:inline">Diperbarui {updated.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' })}</span><button aria-label="Refresh data" onClick={refresh} className="rounded-xl border border-white/10 p-2.5 text-white/60 transition hover:bg-white/10 hover:text-white"><RefreshCw size={17} className={loading ? 'animate-spin' : ''}/></button><button aria-label="Fullscreen" onClick={goFullscreen} className="hidden rounded-xl border border-white/10 p-2.5 text-white/60 transition hover:bg-white/10 hover:text-white sm:block"><Maximize2 size={17}/></button></div></header>
    <section className="mx-auto max-w-[1500px] px-6 py-10 sm:px-10 lg:px-16 lg:py-14"><div className="mb-8 flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="mb-4 text-xs font-bold uppercase tracking-[.2em] text-[#a696ff]">Replay voting day</p><h1 className="flex max-w-[1000px] flex-wrap items-baseline gap-x-3 gap-y-1 text-4xl font-black tracking-tight sm:text-6xl"><span>Vote Announcement</span><span className="text-white/45">Pemilihan Ketua & Wakil OSIS</span></h1></div><div className="rounded-2xl border border-[#7657e8]/40 bg-[#211a42] px-5 py-4"><p className="text-xs text-white/45">Peserta sekarang / total vote peserta</p><p className="mt-1 text-3xl font-black">{total.toLocaleString('id-ID')} / {totalVotes.toLocaleString('id-ID')}</p><p className="mt-1 text-sm font-bold text-[#a696ff]">{stage}% suara diumumkan</p></div></div>
      <div className="mb-8 rounded-3xl border border-white/10 bg-white/[.04] p-4 sm:p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-white/45">Tahap pengumuman</p><p className="mt-1 text-xl font-black">{stage}% suara masuk</p></div><div className="flex items-center gap-2"><button aria-label="Reset replay" onClick={reset} className="rounded-xl border border-white/10 p-2.5 text-white/65 hover:bg-white/10 hover:text-white"><RotateCcw size={17}/></button><button aria-label={playing ? 'Pause replay' : 'Play replay'} onClick={() => setPlaying(value => !value)} className="flex items-center gap-2 rounded-xl bg-[#7657e8] px-4 py-2.5 text-sm font-bold hover:bg-[#866cf0]">{playing ? <Pause size={16}/> : <Play size={16}/>} {playing ? 'Pause' : 'Play'}</button></div></div><div className="grid grid-cols-4 gap-2">{stages.map((value, index) => <button key={value} onClick={() => { setStageIndex(index); setPlaying(false) }} className={`rounded-xl px-3 py-3 text-sm font-black transition ${index === stageIndex ? 'bg-[#7657e8] text-white' : 'bg-white/[.06] text-white/45 hover:bg-white/10 hover:text-white'}`}>{value}%</button>)}</div><div className="mt-3 flex justify-between gap-2"><button aria-label="Previous stage" disabled={stageIndex === 0} onClick={() => { setStageIndex(index => index - 1); setPlaying(false) }} className="flex items-center gap-1 text-xs font-bold text-white/50 disabled:opacity-30"><ChevronLeft size={15}/> Sebelumnya</button><span className="text-xs text-white/30">{playing ? 'Berjalan otomatis' : 'Dikendalikan presenter'}</span><button aria-label="Next stage" disabled={stageIndex === stages.length - 1} onClick={() => { setStageIndex(index => index + 1); setPlaying(false) }} className="flex items-center gap-1 text-xs font-bold text-white/50 disabled:opacity-30">Berikutnya <ChevronRight size={15}/></button></div></div>
      <div className="grid gap-5 md:grid-cols-2">{candidates.map((candidate, index) => { const percent = total ? candidate.count / total * 100 : 0; const [ketuaImage, wakilImage] = candidateImages(candidate); return <article key={candidate.label} className={`relative overflow-hidden rounded-[28px] border p-5 transition ${index === 0 && candidate.count > 0 ? 'border-[#7657e8]/70 bg-[#211a42]' : 'border-white/10 bg-white/[.06]'}`}><div className="flex items-center gap-5"><div className="relative flex h-28 w-32 shrink-0 items-end justify-center gap-2"><div className="h-24 w-20 overflow-hidden rounded-2xl border border-white/10 bg-white/10">{ketuaImage ? <img src={ketuaImage} alt={`Foto ${candidate.namaKetua || candidate.label}`} className="h-full w-full object-cover"/> : <div className="flex h-full items-center justify-center text-2xl font-black text-white/25">{(candidate.namaKetua || candidate.label).charAt(0)}</div>}</div><div className="h-24 w-20 overflow-hidden rounded-2xl border-2 border-[#100d1f] bg-white/10 shadow-lg shadow-black/20">{wakilImage ? <img src={wakilImage} alt={`Foto ${candidate.namaWakil || 'Wakil calon'}`} className="h-full w-full object-cover"/> : <div className="flex h-full items-center justify-center text-2xl font-black text-white/25">{(candidate.namaWakil || 'W').charAt(0)}</div>}</div><span className="absolute left-2 top-2 rounded-lg bg-black/40 px-2 py-1 text-[10px] font-bold">#{index + 1}</span></div><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-[.18em]" style={{color:candidate.color}}>Pasangan calon</p><h2 className="mt-2 truncate text-xl font-black sm:text-2xl">{candidate.label}</h2><p className="mt-1 truncate text-sm text-white/50">{candidate.namaKetua}{candidate.namaWakil ? ` & ${candidate.namaWakil}` : ''}</p></div><div className="text-right"><p className="text-3xl font-black">{candidate.count.toLocaleString('id-ID')}</p><p className="text-sm font-bold" style={{color:candidate.color}}>{percent.toFixed(1)}%</p></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full transition-all duration-700" style={{width:`${percent}%`, backgroundColor:candidate.color}}/></div></article> })}</div>{candidates.length === 0 && <div className="rounded-3xl border border-dashed border-white/15 py-20 text-center text-white/45">Menunggu data hasil pemilihan...</div>}<footer className="mt-10 flex justify-between text-xs text-white/30"><span>Replay suara dari vote pertama hingga terakhir</span><span>SMA Islam Al Azhar 16</span></footer></section>
  </main>
}
